name: productsplat
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - plyfile
  - cudatoolkit=11.6
  - tqdm
  - pip:
    - pycolmap
    - sentencepiece
    - transformers
    - tensorflow[and-cuda]
    - opencv-python
    - modelscope
    - tensorflow[and-cuda]